FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY . /app
WORKDIR /app

FROM base AS deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base AS build
RUN ls | echo
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run -r build

FROM base AS common
COPY --from=deps /app/packages/common/node_modules/ /app/packages/common/node_modules
COPY --from=build /app/packages/common/dist /app/packages/common/dist

FROM common AS server
COPY --from=deps /app/packages/server/node_modules/ /app/packages/server/node_modules
WORKDIR /app/packages/server
CMD [ "pnpm", "dev" ]

FROM common AS web
COPY --from=deps /app/packages/web/node_modules/ /app/packages/web/node_modules
WORKDIR /app/packages/web
CMD [ "pnpm", "start" ]

FROM nginx:latest AS proxy
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
